### ISSUE TITLE
Shouldn't need to monkey patch xlsx->tabdelimited2 and the like into spork

### ISSUE THREAD

**Issue by joinr** [fsdonks/demand_builder#12]
Updated API allows general overriding of starting line to read from, as well as read-cell behavior: 

https://github.com/joinr/spork/blob/d017e1a9b64bb4b51d17d781c46ff59ce75c45c5/src/spork/util/excel/core.clj#L287

spork.util.excel.core/xlsx->tabdelimited  should be sufficient.
@fs-craig  @mpavlak1

**Comment by mpavlak1** [comment]
Still needed the skipped non-tabular rows because they still contain formatting information.
In SRC_By_Day, the first row is the phase timings (non-tabular) and the second row is the header. 
Needed to start reading the tabular region based on the second row, but did not want to drop the first row.
Redefined tabular-region and commented out dropping the skipped lines (line 196 in excel.core)  so did not lose the phase timing information.
@fs-tom
